pull_request_rules:
  - name: Request reviews and label Steward's PRs
    conditions:
      - author=Tofu-bot
    actions:
      request_reviews:
        users: [ Odomontois, road21, KS2003, saladNights, mikhailchuryakov, skye17]
      label:
        add: [ dependency-update ]

  - name: Merge Steward's PRs
    conditions:
      - author=Tofu-bot
      - or:
          - and:
              - "#files=1"
              - or:
                  - files=project/build.properties
                  - files=project/plugins.sbt
          - body~=labels:.*semver-patch
          - "#approved-reviews-by>=1"
      - check-success~=Test \(ubuntu-latest, 3\.1\.\d+, temurin@17\)
    actions:
      merge:
        method: rebase

  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
